package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

const generatedHeader = "// Code generated by spdmgen. DO NOT EDIT.\n\n"

// writeOrVerify writes generated Go source to a file, or verifies it matches
// the existing file content when verify is true.
func writeOrVerify(
	filePath string,
	content []byte,
	verify bool,
) error {
	formatted, err := format.Source(content)
	if err != nil {
		return fmt.Errorf("gofmt %s: %w\nraw content:\n%s", filePath, err, content)
	}

	if verify {
		existing, err := os.ReadFile(filePath)
		if err != nil {
			return fmt.Errorf("verify: cannot read %s: %w", filePath, err)
		}
		if !bytes.Equal(existing, formatted) {
			return fmt.Errorf("verify: %s differs from generated output", filePath)
		}
		fmt.Fprintf(os.Stderr, "  verified %s\n", filePath)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(filePath), err)
	}

	if err := os.WriteFile(filePath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", filePath, err)
	}

	fmt.Fprintf(os.Stderr, "  wrote %s\n", filePath)
	return nil
}
